##
# This is the default full text search query for repositories without text index.
#
# It searches in term and vocabulary labels and uses a plain string lowercase containment.
##

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?label ?type ?vocabularyUri WHERE {
    {
        ?entity a ?term ;
           rdfs:label ?label ;
           ?inVocabulary ?vocabularyUri .
        BIND (?term as ?type) .
    } UNION {
        ?entity a ?vocabulary ;
           rdfs:label ?label .
        BIND (?vocabulary as ?type) .
    }
    FILTER CONTAINS(LCASE(?label), LCASE(?searchString)) .
} ORDER BY ?label