PREFIX :<http://www.openrdf.org/contrib/lucenesail#>
PREFIX pdp:<http://onto.fel.cvut.cz/ontologies/slovnik/agendovy/popis-dat/pojem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?label ?snippetField ?score ?type ?vocabularyURI WHERE {
  
     ?search :query ?searchString;
       :score ?score;
       :snippet ?snippetField .  
  
    ?entity :matches ?search .
    ?entity a ?type .
  	?entity rdfs:label ?label .
  
  OPTIONAL {
        ?entity pdp:je-pojmem-ze-slovniku ?vocabularyURI .
    }
    FILTER (?type = pdp:term || ?type = pdp:slovnik)
  
}
ORDER BY desc(?score)