PREFIX : <http://www.ontotext.com/connectors/lucene#>
PREFIX inst: <http://www.ontotext.com/connectors/lucene/instance#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pdp:<http://onto.fel.cvut.cz/ontologies/slovnik/agendovy/popis-dat/pojem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?label ?snippetText ?snippetField ?score ?type ?vocabularyURI {
  ?search a inst:czech_index ;
      :query ?searchString ;
      :entities ?entity .
    ?entity rdfs:label ?label .
  ?entity a ?type .
  ?entity :score ?score .
  ?entity :snippets _:s .
        _:s :snippetText ?snippetText .
    _:s :snippetField ?snippetField .
    OPTIONAL {
        ?entity pdp:je-pojmem-ze-slovniku ?vocabularyURI .
    }
    FILTER (?type = pdp:term || ?type = pdp:slovnik)
          
}
ORDER BY desc(?score)