PREFIX g: <__VOC_IRI__>

PREFIX v-sgov-pojem: <https://slovník.gov.cz/veřejný-sektor/pojem/>
PREFIX popis-dat-pojem: <http://onto.fel.cvut.cz/ontologies/slovnik/agendovy/popis-dat/pojem/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
DELETE {
    ?x dc:created ?y .
	?c dc:created ?y2 .
	?d dc:created ?y3 .
	?c dc:relation ?src ;
	   skos:prefLabel ?l;
	   dc:description ?cComment .
}
INSERT {
    GRAPH g: {
    ?x a popis-dat-pojem:dokumentový-slovník ;
       popis-dat-pojem:má-glosář ?g ;
       popis-dat-pojem:má-model ?m ;
       popis-dat-pojem:popisuje-dokument ?d ;
       popis-dat-pojem:má-autora ?a ;
       popis-dat-pojem:má-datum-a-čas-vytvoření ?t ;
       rdfs:label ?vTitle .

    ?d a popis-dat-pojem:dokument ;
       rdfs:label ?dTitleCs ;
       dc:description ""@cs ;
       popis-dat-pojem:má-autora ?a ;
       popis-dat-pojem:má-datum-a-čas-vytvoření ?t ;
       popis-dat-pojem:má-soubor ?s .

    ?s a popis-dat-pojem:soubor ;
       rdfs:label ?sTitleCs ;
       dc:description ""@cs ;
       popis-dat-pojem:má-autora ?a ;
       popis-dat-pojem:má-datum-a-čas-vytvoření ?t .

    ?m a popis-dat-pojem:model .
    ?g a popis-dat-pojem:glosář .
    ?c a popis-dat-pojem:term ;
       rdfs:label ?l ;
       rdfs:comment ?cComment ;
       popis-dat-pojem:má-autora ?a ;
       popis-dat-pojem:má-datum-a-čas-vytvoření ?t ;
       dc:source ?srcd ;
       popis-dat-pojem:je-pojmem-ze-slovníku ?x .
    ?g popis-dat-pojem:obsahuje-kořenový-pojem ?cTop .
    }
} WHERE {
    GRAPH g: {
    ?x a v-sgov-pojem:slovník ;
       v-sgov-pojem:má-glosář ?g ;
       v-sgov-pojem:má-model ?m ;
       dc:title ?vTitle .
    ?c skos:inScheme ?g .
	FILTER(lang(?vTitle)="cs")
    OPTIONAL {
        ?c dc:description ?cComment .
	}
    OPTIONAL {
        ?c skos:prefLabel ?l .
  }
    OPTIONAL {
        ?x dc:created ?y .
	}
    OPTIONAL {
        ?c dc:created ?y2 .
	}
    OPTIONAL {
        ?c dc:relation ?src .
        BIND (str(?src) as ?srcd)
	}
    OPTIONAL {
        FILTER NOT EXISTS {
            ?c skos:broader|^skos:narrower ?cSuper.
            FILTER (strstarts(str(?cSuper),g:))
        }
        BIND( ?c AS ?cTop )
	}
    BIND (<http://onto.fel.cvut.cz/ontologies/uzivatel/michal-med> as ?a)
    BIND (iri(concat(str(?x),"/document")) as ?d)
    BIND (strlang(concat("Dokument pro ",str(?vTitle)),"cs") as ?dTitleCs)
    BIND (strlang(concat("Document for ",str(?vTitle)),"en") as ?dTitleEn)
    BIND (iri(concat(str(?d),"/file")) as ?s)
    BIND (strlang(concat("Soubor pro ",str(?vTitle)),"cs") as ?sTitleCs)
    BIND (strlang(concat("File for ",str(?vTitle)),"en") as ?sTitleEn)
    BIND (NOW() as ?t)
    OPTIONAL {
        ?d dc:created ?y3 .
	}
}
}
