# Replace skos:narrower by skos:broader
#
PREFIX g: <__VOC_IRI__>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
    GRAPH g: {
        ?t skos:broader ?b .
	}
} INSERT {
    GRAPH g: {
		?b skos:narrower ?t.
    }
} WHERE {
    GRAPH g: {
        ?t skos:broader ?b .
	}
}