;# Rename the vocabulary to be TermIt compliant. TermIt uses fragments to identify vocabularies and thus, the fragment needs to be different than 'slovník'

PREFIX g: <__VOC_IRI__>
PREFIX base: <__VOC_IRI__/>

DELETE {
    base:slovník ?p ?o .
}
INSERT {
    GRAPH g: {
		g: ?p ?o .
    }
} WHERE {
    GRAPH g: {
        base:slovník ?p ?o .
	}
}
